# @Author: Zak Zhu
# @Date:   2021-02-23 16:13:34
# @Last Modified by:   Zak Zhu
# @Last Modified time: 2021-02-23 17:04:50
---
- name: "{{ playbook_dir | basename }}"
  hosts: localhost
  remote_user:
  gather_facts: yes
  vars:
    status: "{{ ansible_local[stats_file_name]['status'] | default('0') }}"
  force_handlers: no
  pre_tasks:
    - name: update ansible facts
      setup:
        gather_subset:
          - "all"

    - when: status == '0'
      block:
        - import_role:
            name: pre_roles/common
          tags:
            - pr_r_common
        - meta: flush_handlers

  tasks:
    - when: status == '0'
      block:
        - import_role:
            name: hostname
          tags:
            - r_hostname
        - meta: flush_handlers

        - import_role:
            name: swap_file
          tags:
            - r_swap_file
        - meta: flush_handlers

        - import_role:
            name: data_volumes
          tags:
            - r_data_volumes
        - meta: flush_handlers

  post_tasks:
    - when: status == '0'
      block:
        - import_role:
            name: post_roles/common
          tags:
            - po_r_common
        - meta: flush_handlers
