---
- name: <r_oracle_preinst_t_common> configure oracle linux with oracle preinstallation rpm
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
    disable_gpg_check: yes
    #allow_downgrade: yes
  loop: "{{ oracle_preinst_pkgs }}"

- name: <r_oracle_preinst_t_common> load settings from all system configuration files
  command:
  #become: yes
  #become_method: su
  #become_user:
  #become_flags: "-s /bin/sh"
  args:
    cmd: sysctl --system
    #chdir:
    # A filename or (since 2.0) glob pattern.
    # If it already exists, this step *won't* be run.
    #creates:

    # A filename or (since 2.0) glob pattern.
    # If it already exists, this step *will* be run.
    #remove:
